### PR TITLE
fixing some simple bugs

### PR DESCRIPTION
**Pull request by eilifm**

### CODE REVIEW

**Comment by azeemba** [comment]
Hi! Thanks for the PR! What is the bug this is causing?

**Comment by eilifm** [comment]
Packages was missing commander

Calling balances threw a SQL error so I added the column.

**Comment by eilifm** [comment]
Also, it doesn’t seem to get transactions far back.  Might be due to development account.

**Comment by eilifm** [comment]
Also, please add a license.  Preferably MIT, Apache or BSD.

**Comment by azeemba** [comment]
I certainly appreciate the PR but I just want to make sure you have also seen this: https://github.com/yyx990803/build-your-own-mint

It also uses plaid API access but seems to be a lot more active. I found plaid's behavior to be very buggy and eventually just gave up so this project is not as well maintained.

**Comment by eilifm** [comment]
I'm hoping that their product has gotten better since you last worked with it. I have friends there (not engineers) and they seem to think customer satisfaction fairly high. It is also one of the only games in town for pulling this kind of financial data.

**Pull request merged**
